easy_admin:
    user:
        # this will look for getFullName(), isFullName(), ..., and 'fullName' property
        name_property_path: 'userName'
    design:
        brand_color: '#3B5998'
    entities:
        Article:
            # ...
            label: 'article'
            list:
                actions:
                    - {name: 'delete', label: 'del' }
                    - {name: 'edit' , lable: 'edite'}
                title: 'article'
                fields:
                    - id
                    - title
                    - createdAt
                    - commentaires
                    - { property: 'image', type: 'image', base_path: '%app.path.article_images%' }
            show:
                fields:
                    - { property: 'image', type: 'image', base_path: '%app.path.article_images%' }
            form:
                fields:
                    - title
                    - content
                    - createdAt
                    - category
                    - link
                    - { property: 'imageFile', type: 'vich_file' }
            class: App\Entity\Article
            # ...
        Category:
            class: App\Entity\Category
        User:
            class: App\Entity\User
        Commentaire:
            class: App\Entity\Commentaire

